version: "3.9"

services:
  frontend:
    container_name: mohsen
    image: nginx:alpine
    restart: always
    volumes:
      - ./configs:/etc/nginx/conf.d
      - ./out:/project
    ports:
      - 3008:80
